### ISSUE TITLE
RFC: Filter out classes already taken

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#1028]
## Description
- Using data from PeterPortal, filter out classes that came before the current quarter quarter in the four-year plan.
- This would probably involve an actual PeterPortal API (as opposed to AAPI).
- My current imagination is that AA backend would authenticate the user with Google, request PPAPI server-side with a shared secret for the four-year plan, then request the AAPI to filter out those classes.

## Tasks
- [x] Specify the user interactions for the feature (Minh).
    - For UI, I'd imagine it's just a toggle in the search pane that's only visible if you're authenticated.
    - However, we have to think about how to communicate the idea that the data is pulled from PeterPortal.
- [x] Work out communications between PP and AA.
    - What if someone has multiple 4-year plans in PeterPortal?
- [ ] Decide on a timeline.
- [x] Implement the logic to filter out classes depending on the user *on the backend* (with authentication).
    - Complete by Wednesday 2/12 
- [x] Implement the feature on the frontend.

## Related Issues
- Requires #1027

**Comment by MinhxNguyen7** [comment]
@js0mmer could you comment on this?

**Comment by js0mmer** [comment]
Sounds reasonable. I'll create an issue for it. To clarify:
* We'll set up a REST endpoint in our API for querying previously taken courses that takes a google account id and the current quarter as params
* We'll verify a secret key that is passed in the Authorization header so only AA can use this endpoint
* We'll return a string[] of course ids for all courses that come before the specified quarter in the user's planner(s)

**Comment by MinhxNguyen7** [comment]
Yes. What is the course ID though? It has to be the course title right? I.e., "ICS 33"

**Comment by js0mmer** [comment]
Yes, I mean the ID as AnteaterAPI has it defined for each course. So "I&CSCI33"
