### ISSUE TITLE
ZotCourse Feature Parity

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#440]
I've seen a lot of people using [ZotCourse](https://zotcourse.appspot.com/), which is a similar schedule planning website to ours. It has some features that would fit well in AntAlmanac that should be on our roadmap to implement:

- [x] resizable menus: #431
- [x] gpa and grade distribution in search results #671 
- [x] ~~sort by columns~~
- [x] hide certain columns #624 
- [ ]~~it has "search on eaterevals". we removed this feature, but it might be worth investigating how ZotCourse implements it.~~
- [x] ~~"recent schedules": shows the most recent schedules loaded in the load menu. Depending on how we change the project with Google sign-ins, this might be incompatible with our sign-in system.~~
- [x] donation button #892 
- [x] import from zotcourse: #474

 

We can resolve this issue once we've implemented all those features. The last 3 need further investigation for utility and feasibility, but the first ones we should definitely do.

**Comment by MinhxNguyen7** [comment]
Search on EaterEvals doesn't work on ZotCourse. The URL format is currently https://evaluations.eee.uci.edu/eaterevals/browse/instructor/[INSTRUCTOR_ID]. Instructor ID might be searchable per info in #174 

I like the donation button. Maybe eventually we'll get enough to buy a pizza.

I'm looking into importing from ZotCourse. It seems pretty feasible. We should discuss the utility more.

**Comment by EricPedley** [comment]
We're gonna shelve sort by columns because there's only really two columns we'd want to be able to sort by: GPA and RMP. GPA would be useful but a pain in the ass to implement because of how it has to manipulate the table intrustively, and automatically getting the RMP ratings isn't working because RMP changed how the IDs work.

If anyone really wants to implement GPA sorting they can do it but we're de-prioritizing it.

**Comment by EricPedley** [comment]
Recent schedules will be covered under the google auth changes.
