### ISSUE TITLE
WebSOC goes live 2/10

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#893]
## To-Dos
- [ ] Update `termData.ts` with the [correct start date](https://www.reg.uci.edu/calendars/quarterly/2023-2024/quarterly23-24.html)
- [ ] Update test snapshots to reflect the current term, similar to [this](https://github.com/icssc/AntAlmanac/pull/809/files)
- [ ] After adding a new term, use `termData[defaultTerm+1]` for the function `getFinalsStartDate()` (also in `termData.ts`), since we don't want it to start using spring's finals calendar

## Future Followup
- Figure out how to not do this `defaultTerm-1` shenanigan; @adcockdalton, thoughts on diving into this one? Open a new issue and write a nice workaround (maybe check that the current time is after the current term, else go down the list (?))
