### ISSUE TITLE
AANTS Backend

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#971]
## Description
- Implement the backend for AntAlmanac Notification System (AANTS).
- AA will periodically poll AAPI for section changes. 
    - [Discussion](https://github.com/icssc/AntAlmanac/discussions/1071#discussioncomment-11495507) of the details of the API communications 
- The polling script must be robust and also update with new PRs as part of our CI pipeline.
    - I.e., it _cannot_ be an EC2 instance with a cron job.
    - We probably want to add another lambda as part of our stack (equivalent to another backend) that is triggered by a CloudWatch event. See [this](https://edwinradtke.com/eventtargets).

### Requirements
See discussion below.

### Open Questions
- When, exactly, should we send a notification?
   - What if a section opens, then closes, then opens again? 
- How will we send emails? SNS or another service?
- From which email are we sending? Would it be proper to use the `icssc@uci.edu` email address?

### Database
- Install postgres and pgAdmin [instructions](https://medium.com/@marvinjungre/get-postgresql-and-pgadmin-4-up-and-running-with-docker-4a8d81048aea)
- Follow backend.

## Tasks
- [x] Define requirements.
- [x] Set up the database locally.
- [x] Implement the script which polls AAPI, checks the subscriptions, and triggers notification sending.
    - As a dummy, just print the emails to the terminal
- [x] Design the cloud architecture.
- [x] Implement email-sending.
- [ ] Implement and integrate cloud system into CDK.
- [ ] Implement endpoint with auth for users to subscribe to a notification.
    - This will have to wait for auth to be finished (F2F).

## Related Issues
- Requires #970 
- Requires #229 

## Useful Information
- The stack where we will add the resources is in `apps/cdk/src/stacks/backend.ts`.

**Comment by MinhxNguyen7** [comment]
I just have two modifications to the requirements:
- The user should be able to sign up for open, wait-list, and/or full, not just all notifications. 
- The user should also be able to sign up for a change of restrictions.

The other requirements should be updated accordingly. Also, can you move the requirements to a discussion? That would be a better place for it, seeing how much space it is in the issue and the fact that it's not only to do with the backend

**Comment by IsaacNguyen** [comment]
> I just have two modifications to the requirements:
> 
> * The user should be able to sign up for open, wait-list, and/or full, not just all notifications.
> * The user should also be able to sign up for a change of restrictions.
> 
> The other requirements should be updated accordingly. Also, can you move the requirements to a discussion? That would be a better place for it, seeing how much space it is in the issue and the fact that it's not only to do with the backend

Yeah sounds good! About the change of restrictions part, I saw no mention of AAPI signaling when class restrictions are dropped in [the discussion we had with AAPI](https://github.com/icssc/AntAlmanac/discussions/1071#discussioncomment-11495507). Would we have to call a separate AAPI endpoint for this or are class restrictions going to be an added output from the one we will be calling? Adding onto this, the only restriction we will be worrying about is the major-only restriction, right? I know there are other types of restrictions for classes but this is the only one I know about that makes sense.

**Comment by IsaacNguyen** [comment]
### Requirements
- There will be a button for each course allowing a user to sign up for a notification subscription on the Added tab. They have the option to opt in for notifications when the class has requirement code changes, opens, becomes waitlisted, and/or becomes full. They can select only one or multiple.
- There can be a little tab to view all classes that the user has notification subscriptions for the quarter. 
- Notifications about a current quarter's classes will stop being sent following the end of the second week of instruction (the deadline for to add/drop classes).
- The user can have the option to remove their notification subscription from a certain class from the Added tab, preventing them from receving further email notifications.
- Check changes and notify for current and all subsequent terms
- There will only be ONE email format that is sent. Based on whatever they are subscribed to, they can receive emails for individual changes (just waitlist, open, full, or code changes) OR multiple (waitlist and code change, open and code change, etc.)
 - <img width="1094" alt="Image" src="https://github.com/user-attachments/assets/0a1bd992-0a91-439d-abf8-3748302f7603" />
 - The subject line of each should contain the class name and say it has had enrollment changes.
 - Assuming we use AWS SES, the emails will be sent via `icssc@uci.edu`. Otherwise, it could be sent from an AntAlmanac email (assuming we have one).
 - The email itself should greet the person (assuming we have their name), say how recent this information was gathered (time and date), mention the course name, time slot, and course code, and give the user a link to WebReg and AntAlmanac.
 - No email will be sent if the class goes from OPEN to OPEN or FULL/WAITLISTED to FULL/WAITLISTED

**Comment by MinhxNguyen7** [comment]
> I saw no mention of AAPI signaling when class restrictions are dropped

You should communicate that to them so they can add that as part of the response

**Comment by IsaacNguyen** [comment]
> > I saw no mention of AAPI signaling when class restrictions are dropped
> 
> You should communicate that to them so they can add that as part of the response

Got it. Just made a comment in the discussion.

**Comment by IsaacNguyen** [comment]
> > I saw no mention of AAPI signaling when class restrictions are dropped
> 
> You should communicate that to them so they can add that as part of the response

[According to Andrew](https://github.com/icssc/AntAlmanac/discussions/1071#discussioncomment-11635824), it doesn't look like they can implement that unfortunately.

**Comment by IsaacNguyen** [comment]
![Image](https://github.com/user-attachments/assets/ba9ddb5e-5442-4987-b9d2-8ff1f8377dfa)
These were the requirements I was thinking about for the AANTS frontend. Let me know what you guys think.

**Comment by MinhxNguyen7** [comment]
Looks good. I can forward that to UI/UX and see if they can do that in a reasonable time frame.

For my sake, can you copy all of that as text to the #761 issue?
